export const TeamMember = [
  { key: "ericaZheng-5", headshot: "https://media.licdn.com/dms/image/v2/D4E03AQE2aDDSJhCxTg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1730701214676?e=1762992000&v=beta&t=5GKoy-ul3ZgDqQ3Sc0hxGpuzkfHbWOK6I3k1_V5-cDM", name: "Erica Zheng", position: "Marketing & Events Director", team: "E-Board", linkedin: "https://www.linkedin.com/in/zhengerica/", alt: "" },
  { key: "xavierYu-20", headshot: "https://media.licdn.com/dms/image/v2/D5603AQElSyoIX6XMyA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1727737161830?e=1762992000&v=beta&t=jZDMwAcdCSD7IsfPD638ooEQExPzC91AqnC9Y-cnqkc", name: "Xavier Yu", position: "Director of Research", team: "Research Team", linkedin: "https://www.linkedin.com/in/xavier-yu/", alt: "" },
  { key: "aileenRuan-1", headshot: "", name: "Aileen Ruan", position: "Events Coordinator", team: "Events Team", linkedin: "", alt: "" },
  { key: "arjunSikka-2", headshot: "", name: "Arjun Sikka", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "atulyaKathuria-3", headshot: "", name: "Atulya Kathuria", position: "Outreach Coordinator", team: "Outreach Team", linkedin: "", alt: "" },
  { key: "aidanKelly-4", headshot: "", name: "Aidan Kelly", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "madelineShih-6", headshot: "", name: "Madeline Shih", position: "Research Analyst", team: "Research Team", linkedin: "", alt: "" },
  { key: "georgeFoster-7", headshot: "", name: "George Foster", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "edisonKwok-8", headshot: "", name: "Edison Kwok", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "gordonBie-9", headshot: "", name: "Gordon Bie", position: "", team: "Marketing Team", linkedin: "", alt: "" },
  { key: "vedNaykude-10", headshot: "", name: "Ved Naykude", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "anyaSolanki-11", headshot: "", name: "Anya Solanki", position: "Research Analyst", team: "Research Team", linkedin: "", alt: "" },
  { key: "eitanBerenfeld-12", headshot: "", name: "Eitan Berenfeld", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "cameronRyan-13", headshot: "", name: "Cameron Ryan", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "nicoleSchubert-14", headshot: "", name: "Nicole Schubert", position: "Vice-President", team: "E-Board", linkedin: "", alt: "" },
  { key: "riyaMohandas-15", headshot: "", name: "Riya Mohandas", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "luluYu-16", headshot: "", name: "Lulu Yu", position: "Research Analyst", team: "Research Team", linkedin: "", alt: "" },
  { key: "oliviaYeung-17", headshot: "", name: "Olivia Yeung", position: "Treasurer", team: "E-Board", linkedin: "", alt: "" },
  { key: "kristinaSaavedra-18", headshot: "", name: "Kristina Saavedra", position: "Events Coordinator", team: "Events Team", linkedin: "", alt: "" },
  { key: "harshSingh-19", headshot: "", name: "Harsh Singh", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "nateHarris-21", headshot: "", name: "Nate Harris", position: "Outreach Coordinator", team: "Outreach Team", linkedin: "", alt: "" },
  { key: "nafisaTasnia-22", headshot: "", name: "Nafisa Tasnia", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "wilsonChang-23", headshot: "", name: "Wilson Chang", position: "Research Analyst", team: "Research Team", linkedin: "", alt: "" },
  { key: "aryanSinha-24", headshot: "", name: "Aryan Sinha", position: "", team: "Quant Team", linkedin: "", alt: "" },
  { key: "connorTessaro-25", headshot: "", name: "Connor Tessaro", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "riyaAnanthanpillai-26", headshot: "", name: "Riya Ananthanpillai", position: "Outreach Coordinator", team: "Outreach Team", linkedin: "", alt: "" },
  { key: "abigailEng-27", headshot: "", name: "Abigail Eng", position: "Research Analyst", team: "Research Team", linkedin: "", alt: "" },
  { key: "shireenKumar-28", headshot: "", name: "Shireen Kumar", position: "", team: "Tech Team", linkedin: "", alt: "" },
  { key: "laithBuheiry-29", headshot: "", name: "Laith Buheiry", position: "Events Coordinator", team: "Events Team", linkedin: "", alt: "" },
  { key: "chelseaKwan-30", headshot: "", name: "Chelsea Kwan", position: "Project Manager", team: "Consulting Team", linkedin: "", alt: "" },
];
