export const CARD = [
  // 📌 Fall 2024
  {
    key: "fall2024-1",
    year: "Fall 2024",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/deck/20nOlL3vzRL0htnLVVBZQj/Mist-Presentation?node-id=1-141&t=5dWKL7heI9Fx15Uk-1",
    figmaDeckLink: "https://www.figma.com/deck/20nOlL3vzRL0htnLVVBZQj/Mist-Presentation?node-id=1-141&t=5dWKL7heI9Fx15Uk-1",
    header: "1st: Mist",
    description: "Created by Michael Salzman, Sid Kerkar",
  },
  {
    key: "fall2024-2",
    year: "Fall 2024",
    type: "googleSlides",
    googleSlidesEmbedLink: "https://docs.google.com/presentation/d/1LuCNacdDLT-C9PZmBZWFzP-DwXk-9FHE/embed",
    googleSlidesFullLink: "https://docs.google.com/presentation/d/1LuCNacdDLT-C9PZmBZWFzP-DwXk-9FHE/edit#slide=id.p2",
    header: "2nd: Cliq",
    description: "Created by Ekaterina Levinton, Maggie Chua",
  },
  {
    key: "fall2024-3",
    year: "Fall 2024",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1pxNH_K8n7hwnAmb2PHc3D7OfDxf4KPAa/preview",
    pdfFullLink: "https://drive.google.com/file/d/1pxNH_K8n7hwnAmb2PHc3D7OfDxf4KPAa/view?usp=sharing",
    header: "3rd: LoanPilot",
    description: "Created by Kiki Liu, Sathvika Mudunuri, Shreyashi Kalakuntla, Swar Kewalia, Tyler Kim",
  },

  // 📌 Spring 2024
  {
    key: "spring2024-1",
    year: "Spring 2024",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/proto/j91cczKFxtG5zYh8eVromE/BudgetBound---Disrupt?type=design&node-id=1-2&t=adXd1zctZ3R8XlEm-0&scaling=scale-down&page-id=0%3A1",
    figmaDeckLink: "https://www.figma.com/proto/j91cczKFxtG5zYh8eVromE/BudgetBound---Disrupt?type=design&node-id=1-2&t=adXd1zctZ3R8XlEm-0&scaling=scale-down&page-id=0%3A1",
    header: "1st: Budget Bound",
    description: "Numa Ali, Divya Thoppae, Anya Amin"
  },
  {
    key: "spring2024-2",
    year: "Spring 2024",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/proto/y9ZW2aZuSo8SFqybEOjBFt/Nexcap?type=design&node-id=61-1135&t=Oc6adM9igOZxnO9n-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A126",
    figmaDeckLink: "https://www.figma.com/proto/y9ZW2aZuSo8SFqybEOjBFt/Nexcap?type=design&node-id=61-1135&t=Oc6adM9igOZxnO9n-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A126",
    header: "2nd: Nexcap",
    description: "Arsh Jafri, Vansh Kumar, Rohan Nagpure, Harini Avula, Dishant Budhi"


  },
  {
    key: "spring2024-3",
    year: "Spring 2024",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1Hnx1-E21QFpnlLrv04_ma6-BLS9bnRpN/preview",
    pdfDeckLink: "https://drive.google.com/uc?export=download&id=1Hnx1-E21QFpnlLrv04_ma6-BLS9bnRpN",
    header: "3rd: Payback",
    description: "Jay Jung, Tyler Hwang, Semin Park(Samuel), Nianshao Li(Chris)",
  },
  // 📌 Fall 2023
  {
    key: "fall2023-1",
    year: "Fall 2023",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/proto/mVIGM0W7tta1hjF56F6ymX/Finnovate-Figma?type=design&amp%3Bnode-id=31-198&amp%3Bt=mkaUHUfSrJriEpp8-1&amp%3B",
    figmaDeckLink: "https://www.figma.com/proto/mVIGM0W7tta1hjF56F6ymX/Finnovate-Figma?type=design&amp%3Bnode-id=31-198&amp%3Bt=mkaUHUfSrJriEpp8-1&amp%3B",
    header: "1st: Ceil",
    description: "Keith Yao, Dhruv Reddy, Alex Dong, Jacob Chen",
  },
  {
    key: "fall2023-2",
    year: "Fall 2023",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/CYtj083IZuyBE8tMyaZzyi/Figma-Presentation?node-id=0-1",
    figmaDeckLink: "https://www.figma.com/proto/CYtj083IZuyBE8tMyaZzyi/Figma-Presentation?node-id=0-1&scaling=min-zoom&fullscreen=1",
    header: "2nd: Echo",
    description: "Trisha Garg, Aaryan Jain. Amaya Malik",
  },
  {
    key: "fall2023-3",
    year: "Fall 2023",
    type: "canva",
    canvaEmbedLink: "https://www.canva.com/design/DAF0eO_7Nyg/1rrxoFmCykwyZXteqpWM8g/view?embed",
    canvaFullLink: "https://www.canva.com/design/DAF0eO_7Nyg/1rrxoFmCykwyZXteqpWM8g/view?fullscreen",
    header: "3rd: Sustania",
    description: "Shadeh Jaberi, Daman Anand, Jacky Mora Isa",
  },

  // 📌 Spring 2023
  {
    key: "spring2023-1",
    year: "Spring 2023",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/preview",
    pdfDeckLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/view?usp=sharing",
    header: "1st: Paypause",
    description: "Yvonne Lin, Crystal Chu, Neha Sriram,Ming Jun Gong",
  },
  {
    key: "spring2023-2",
    year: "Spring 2023",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/preview",
    pdfDeckLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/view?usp=sharing",
    header: "2nd: Countable",
    description: "Nina Christofilis",
  },
  {
    key: "spring2023-3",
    year: "Spring 2023",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1DKKlkOmKbK494hE-kehZgX4Xd8HGfLvb/preview",
    pdfDeckLink: "https://drive.google.com/uc?export=download&id=1DKKlkOmKbK494hE-kehZgX4Xd8HGfLvb/view?usp=sharing",
    header: "3rd: Pinocchio",
    description: "Philip Leung, Xavier Yu, Alex Choi, Tarun Anbarasu",
  },
  // 📌 Fall 2022
  {
    key: "fall2022-1",
    year: "Fall 2022",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1V5qj19oZVbiUozTKXoid_gkkZbGxK4JV/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1V5qj19oZVbiUozTKXoid_gkkZbGxK4JV/view?usp=sharing",
    header: "1st: Papaya",
    description: "Fleur Hendriks, Aditya Jain",
  },
  {
    key: "fall2022-2",
    year: "Fall 2022",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/preview",
    pdfDeckLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/view?usp=sharing",
    header: "2nd: Lias",
    description: "Aleksis Visockis, Aden Levy, Aden Levy, Noah Jackson",
  },
  {
    key: "fall2022-3",
    year: "Fall 2022",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1pK7PqKQvaGoyXqTDy9WDSIQmix7L0f7L/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1pK7PqKQvaGoyXqTDy9WDSIQmix7L0f7L/view?usp=sharing",
    header: "3rd: Finstop",
    description: "Indra Enkhboldsodon, Sophia Boin, Serene Zuhdi",
  },

  // 📌 Spring 2022
  {
    key: "spring2022-1",
    year: "Spring 2022",
    type: "googleSlides",
    googleSlidesEmbedLink: "https://docs.google.com/presentation/d/1aWcFfRKdYhDjm6Tz1C-Fgb8upoTCdCtZ/embed",
    googleSlidesDeckLink: "https://docs.google.com/presentation/d/1aWcFfRKdYhDjm6Tz1C-Fgb8upoTCdCtZ/edit#slide=id.p1",
    header: "1st: AdValuate",
    description: "WJackson Terrill, Aiden Benjamin, Nathaniel Sawant, Daniel Hsu",
  },
  {
    key: "spring2022-2",
    year: "Spring 2022",
    type: "googleSlides",
    googleSlidesEmbedLink: "https://docs.google.com/presentation/d/1qw0YYYxLK00AhxJaMU0VTM8a343nLIUS/embed",
    googleSlidesDeckLink: "https://docs.google.com/presentation/d/1qw0YYYxLK00AhxJaMU0VTM8a343nLIUS/edit#slide=id.p1",
    header: "2nd: Fination",
    description: "Lucetta Edward, Wesley Ward, Antwan Giovanni Fisher, Kobena Idun",
  },
  {
    key: "spring2022-3",
    year: "Spring 2022",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1Yc_Ml1ksgpIKF-Jt9rz1FKJjG8SL_KdB/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1Yc_Ml1ksgpIKF-Jt9rz1FKJjG8SL_KdB/view?usp=sharing",
    header: "3rd: SmartX",
    description: "Bryan Pitts, Levin Sanchez, Narayan Sharma",
  },
  // 📌 Fall 2021
  {
    key: "fall2021-1",
    year: "Fall 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1gwuTZzy1GHogNWP1xoOqOvhngXQAHRqH/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1gwuTZzy1GHogNWP1xoOqOvhngXQAHRqH/view?usp=sharing",
    header: "1st: Velar",
    description: "Simran Arneja, Ronit Thummaluru, Joseph Cirillo",
  },
  {
    key: "fall2021-2",
    year: "Fall 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1FP4wIV32JF_SoELKGH_YHGU1diWlhtq_/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1FP4wIV32JF_SoELKGH_YHGU1diWlhtq_/view?usp=sharing",
    header: "2nd: Pulse Solutions",
    description: "Craig Johnson, Luciane Muroya",
  },
  {
    key: "fall2021-3",
    year: "Fall 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1euDf211lt0RC9JRm2P_nOuHC-Yyrk10B/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1euDf211lt0RC9JRm2P_nOuHC-Yyrk10B/view?usp=sharing",
    header: "3rd: Algo",
    description: "Lev Mikhaylov, Omar Shoura, Akash Alaparthi",
  },
  // 📌 Spring 2021
  {
    key: "spring2021-1",
    year: "Spring 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1Qt9c9TBtlJjNz9Io_XoXx4-YFJzO3452/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1Qt9c9TBtlJjNz9Io_XoXx4-YFJzO3452/view?usp=sharing",
    header: "1st: GlassHouse",
    description: "Hannah Sumrall, George Bikhazi, Jason Goodman",
  },
  {
    key: "spring2021-2",
    year: "Spring 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1zFldW84_PcnCkdfuaKmlLA9cLbS-9VhN/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1zFldW84_PcnCkdfuaKmlLA9cLbS-9VhN/view?usp=sharing",
    header: "2nd: Flare for All",
    description: "Jeremy Koch, Henry Mouawad, James Schaefer ",
  },
  {
    key: "spring2021-3",
    year: "Spring 2021",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1MNdU9mqfdO93i7UgNzijjuOTMzWzMbcL/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1MNdU9mqfdO93i7UgNzijjuOTMzWzMbcL/view?usp=sharing",
    header: "3rd: Inveschool",
    description: "Ezra Statsky-Frank, Waliya Ahmed, Utsav Patel, Lindsey Latman, Julia Favis",
  },

// 📌 Fall 2020
  {
    key: "fall22020-1",
    year: "Fall 2020",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1rGZqqON86AHbYjTSRiumOZgY-YgAzyGS/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1rGZqqON86AHbYjTSRiumOZgY-YgAzyGS/view?usp=sharing",
    header: "1st: Moon",
    description: "Willem, Ivan Rosales, Xinyu Wu",
  },
  {
    key: "fall2020-2",
    year: "Fall 2020",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1SecoOhIv0bYpp-obfOUbWXKIpqEbgti0/preview",
    pdfDeckLink: "https://drive.google.com/file/d/1SecoOhIv0bYpp-obfOUbWXKIpqEbgti0/view?usp=sharing",
    header: "2nd: Cake",
    description: "Atari, Arian Gokhale, Seungbin (Andy) Jin, John Fallon, and Jack Paolini ",
  },
  {
    key: "fall2020-3",
    year: "Fall 2020",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/preview",
    pdfDeckLink: "https://drive.google.com/file/d/137AJzkhOXqPiln2vwSfzi5Nhuyx-zwDk/view?usp=sharing",
    header: "3rd: Digipay",
    description: "Valencia Pranata, Bennett Thompson",
  },
];

