export const CARD = [
  // 📌 Fall 2024
  {
    key: "fall2024-1",
    year: "Fall 2024",
    type: "figma",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/deck/20nOlL3vzRL0htnLVVBZQj/Mist-Presentation?node-id=1-141&t=5dWKL7heI9Fx15Uk-1",
    figmaDeckLink: "https://www.figma.com/deck/20nOlL3vzRL0htnLVVBZQj/Mist-Presentation?node-id=1-141&t=5dWKL7heI9Fx15Uk-1",
    header: "1st: Mist",
    description: "Created by Michael Salzman, Sid Kerkar",
  },
  {
    key: "fall2024-2",
    year: "Fall 2024",
    type: "googleSlides",
    googleSlidesEmbedLink: "https://docs.google.com/presentation/d/1LuCNacdDLT-C9PZmBZWFzP-DwXk-9FHE/embed",
    googleSlidesFullLink: "https://docs.google.com/presentation/d/1LuCNacdDLT-C9PZmBZWFzP-DwXk-9FHE/edit#slide=id.p2",
    header: "2nd: Cliq",
    description: "Created by Ekaterina Levinton, Maggie Chua",
  },
  {
    key: "fall2024-3",
    year: "Fall 2024",
    type: "pdf",
    pdfEmbedLink: "https://drive.google.com/file/d/1pxNH_K8n7hwnAmb2PHc3D7OfDxf4KPAa/preview\n",
    pdfFullLink: "https://drive.google.com/file/d/1pxNH_K8n7hwnAmb2PHc3D7OfDxf4KPAa/view?usp=sharing",
    header: "3rd: LoanPilot",
    description: "Created by Kiki Liu, Sathvika Mudunuri, Shreyashi Kalakuntla, Swar Kewalia, Tyler Kim",
  },

  // 📌 Spring 2024
  {
    key: "spring2024-1",
    year: "Spring 2024",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/AAAAA",
    figmaDeckLink: "https://www.figma.com/deck/AAAAA",
    header: "Project 4",
    description: "Description for Project 4",
  },
  {
    key: "spring2024-2",
    year: "Spring 2024",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/BBBBB",
    figmaDeckLink: "https://www.figma.com/deck/BBBBB",
    header: "Project 5",
    description: "Description for Project 5",
  },
  {
    key: "spring2024-3",
    year: "Spring 2024",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/CCCCC",
    figmaDeckLink: "https://www.figma.com/deck/CCCCC",
    header: "Project 6",
    description: "Description for Project 6",
  },
  // 📌 Fall 2023
  {
    key: "fall2023-1",
    year: "Fall 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/XXXXX",
    figmaDeckLink: "https://www.figma.com/deck/XXXXX",
    header: "Project 1",
    description: "Description for Project 1",
  },
  {
    key: "fall2023-2",
    year: "Fall 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/YYYYY",
    figmaDeckLink: "https://www.figma.com/deck/YYYYY",
    header: "Project 2",
    description: "Description for Project 2",
  },
  {
    key: "fall2023-3",
    year: "Fall 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/YYYYY",
    figmaDeckLink: "https://www.figma.com/deck/YYYYY",
    header: "Project 2",
    description: "Description for Project 2",
  },

  // 📌 Spring 2023
  {
    key: "spring2023-1",
    year: "Spring 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/AAAAA",
    figmaDeckLink: "https://www.figma.com/deck/AAAAA",
    header: "Project 4",
    description: "Description for Project 4",
  },
  {
    key: "spring2023-2",
    year: "Spring 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/BBBBB",
    figmaDeckLink: "https://www.figma.com/deck/BBBBB",
    header: "Project 5",
    description: "Description for Project 5",
  },
  {
    key: "spring2023-3",
    year: "Spring 2023",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/CCCCC",
    figmaDeckLink: "https://www.figma.com/deck/CCCCC",
    header: "Project 6",
    description: "Description for Project 6",
  },
  // 📌 Fall 2022
  {
    key: "fall2022-1",
    year: "Fall 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/XXXXX",
    figmaDeckLink: "https://www.figma.com/deck/XXXXX",
    header: "Project 1",
    description: "Description for Project 1",
  },
  {
    key: "fall2022-2",
    year: "Fall 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/YYYYY",
    figmaDeckLink: "https://www.figma.com/deck/YYYYY",
    header: "Project 2",
    description: "Description for Project 2",
  },
  {
    key: "fall2022-3",
    year: "Fall 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/YYYYY",
    figmaDeckLink: "https://www.figma.com/deck/YYYYY",
    header: "Project 2",
    description: "Description for Project 2",
  },
  // 📌 Spring 2022
  {
    key: "spring2022-1",
    year: "Spring 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/AAAAA",
    figmaDeckLink: "https://www.figma.com/deck/AAAAA",
    header: "Project 4",
    description: "Description for Project 4",
  },
  {
    key: "spring2022-2",
    year: "Spring 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/BBBBB",
    figmaDeckLink: "https://www.figma.com/deck/BBBBB",
    header: "Project 5",
    description: "Description for Project 5",
  },
  {
    key: "spring2022-3",
    year: "Spring 2022",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/CCCCC",
    figmaDeckLink: "https://www.figma.com/deck/CCCCC",
    header: "Project 6",
    description: "Description for Project 6",
  },
  // 📌 Spring 2020
  {
    key: "spring2020-1",
    year: "Spring 2020",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/AAAAA",
    figmaDeckLink: "https://www.figma.com/deck/AAAAA",
    header: "Project 4",
    description: "Description for Project 4",
  },
  {
    key: "spring2020-2",
    year: "Spring 2020",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/BBBBB",
    figmaDeckLink: "https://www.figma.com/deck/BBBBB",
    header: "Project 5",
    description: "Description for Project 5",
  },
  {
    key: "spring2020-3",
    year: "Spring 2020",
    figmaEmbedLink: "https://www.figma.com/embed?embed_host=figma&url=https://www.figma.com/file/CCCCC",
    figmaDeckLink: "https://www.figma.com/deck/CCCCC",
    header: "Project 6",
    description: "Description for Project 6",
  },
];

